#!/usr/bin/env bash

# Bash Customizations
. /usr/share/autojump/autojump.sh

shopt -s cdspell;
shopt -s nocaseglob;
bind 'set show-all-if-ambiguous on'
bind 'set completion-ignore-case on'
bind 'TAB:menu-complete'

bind '"\e[A":history-search-backward'
bind '"\e[B":history-search-forward'
shopt -s autocd

bind '"\e[6~": menu-complete'
bind '"\e[5~": menu-complete-backward'