#!/usr/bin/env bash


# To source:
# source /home/sahas/Applications/Customization/custom_bash/bash_customizations

custom_dir=$(dirname "${BASH_SOURCE[0]}")
source "$custom_dir/bash_prompt"
source "$custom_dir/bash_shortcuts"
source "$custom_dir/bash_aliases"

# Bash Customizations
. /usr/share/autojump/autojump.sh

# FZF keybindings
source /usr/share/doc/fzf/examples/key-bindings.bash
source /usr/share/bash-completion/completions/fzf
# -- Use fd instead of fzf --

export FZF_DEFAULT_COMMAND="fd --hidden --strip-cwd-prefix --exclude .git"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND="fd --type=d --hidden --strip-cwd-prefix --exclude .git"

# Use fd (https://github.com/sharkdp/fd) for listing path candidates.
# - The first argument to the function ($1) is the base path to start traversal
# - See the source code (completion.{bash,zsh}) for the details.
_fzf_compgen_path() {
  fd --hidden --exclude .git . "$1"
}

# Use fd to generate the list for directory completion
_fzf_compgen_dir() {
  fd --type=d --hidden --exclude .git . "$1"
}

# TODO: Maybe look into https://github.com/junegunn/fzf-git.sh
